### ISSUE TITLE
the lounge is not possible to be lounched since last version of core

### ISSUE THREAD

**Issue by grayve** [hassio-addons/addon-thelounge#167]
# Problem/Motivation

Since I have updated last night to 2023.8.4 the lounge is not able to start and is turning off directly at the start of the service

## Expected behavior

I expect to be able to use the lounge as it's not loading it's impossible to do anything with it for that

## Actual behavior

the service is starting and failing after some minutes:
`    throw error;
    ^
Error: ENOSPC: System limit for number of file watchers reached, watch '/data/thelounge/packages/package.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2343:34)
    at watchPackages (/usr/local/share/.config/yarn/global/node_modules/thelounge/dist/server/plugins/packages/index.js:143:18)
    at Object.loadPackages (/usr/local/share/.config/yarn/global/node_modules/thelounge/dist/server/plugins/packages/index.js:140:5)
    at Server.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/thelounge/dist/server/server.js:190:25)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitListeningNT (node:net:1774:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/data/thelounge/packages/package.json',
  filename: '/data/thelounge/packages/package.json'
}`

## Steps to reproduce

as far as for me, only start the service with the latest home assistant version

## Proposed changes

I propose that you fix this when you have time as you are doing so much for us and this is not critical. So take your time whatever time it is, it'll always be a pleasure to see that you work for the product and our benefits. Again many thanks for all the work Frenk

**Comment by grayve** [comment]
The problem is solved with the latest Core version
