### ISSUE TITLE
Issue Restarting The lounge after an update

### ISSUE THREAD

**Issue by grayve** [hassio-addons/addon-thelounge#201]
# Problem/Motivation

> After some updates The lounge is not available for me for some days

## Expected behavior

> The lounge should restart normally but it does just shut down after some minutes with an error on the logs

## Actual behavior

>Here is the actual error I have when I updated today home assistant.
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: The Lounge
 A self-hosted web IRC client
-----------------------------------------------------------
 Add-on version: 0.19.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (aarch64 / odroid-n2)
 Home Assistant Core: 2024.9.2
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-thelounge: starting
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-nginx successfully started
2024-09-17 07:26:40 [WARN] You are currently running The Lounge as root. We highly discourage running as root!
2024-09-17 07:26:41 [INFO] Users:
2024-09-17 07:26:41 [INFO] 1. grayve
2024-09-17 07:26:42 [WARN] You are currently running The Lounge as root. We highly discourage running as root!
2024-09-17 07:26:43 [INFO] Retrieving information about the package...
2024-09-17 07:26:44 [INFO] Installing thelounge-theme-solarized v1.1.9...
2024-09-17 07:26:45 [INFO] thelounge-theme-solarized v1.1.9 has been successfully installed.
s6-rc: info: service init-thelounge successfully started
s6-rc: info: service thelounge: starting
s6-rc: info: service thelounge successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[09:26:45] INFO: Starting The Lounge server..
s6-rc: info: service legacy-services successfully started
2024-09-17 07:26:45 [WARN] You are currently running The Lounge as root. We highly discourage running as root!
2024-09-17 07:26:47 [INFO] The Lounge v4.4.3 (Node.js 18.20.4 on linux arm64)
2024-09-17 07:26:47 [INFO] Configuration file: /data/thelounge/config.js
2024-09-17 07:26:47 [INFO] Available at http://[::]:15100/ in private mode
2024-09-17 07:26:47 [INFO] Package thelounge-theme-solarized v1.1.9 loaded
node:internal/fs/watchers:255
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/data/thelounge/packages/package.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2418:34)
    at watchPackages (/usr/local/share/.config/yarn/global/node_modules/thelounge/dist/server/plugins/packages/index.js:143:18)
    at Object.loadPackages (/usr/local/share/.config/yarn/global/node_modules/thelounge/dist/server/plugins/packages/index.js:140:5)
    at Server.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/thelounge/dist/server/server.js:190:25)
    at Object.onceWrapper (node:events:631:28)
    at Server.emit (node:events:529:35)
    at emitListeningNT (node:net:1851:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/data/thelounge/packages/package.json',
  filename: '/data/thelounge/packages/package.json'
}

Node.js v18.20.4
[09:26:47] INFO: Service The Lounge exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[09:26:47] INFO: Service NGINX exited with code 256 (by signal 15)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service thelounge: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service thelounge successfully stopped
s6-rc: info: service init-thelounge: stopping
s6-rc: info: service init-thelounge successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

## Steps to reproduce

> Just restart home assistant after an update

## Proposed changes

> Sorry I have no solution here as I'm not as experienced as you in developments.

**Comment by grayve** [comment]
Additional information.

After a hard reset the issue is solved by itself...
